# Generated by Django 5.0.6 on 2024-06-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_language_short_tutorialname_meme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(max_length=20000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
